apiVersion: apps/v1
kind: Deployment
metadata:
  name:  local-web
  namespace: default
  labels:
    app:  local-web
spec:
  selector:
    matchLabels:
      app: local-web
  replicas: 1
  template:
    metadata:
      labels:
        app:  local-web
    spec:
      containers:
      - name:  local-web
        image:  nginx
        ports:
          - name: web 
            containerPort: 80
        volumeMounts:
          - name: local
            mountPath: /usr/share/nginx/html
      volumes: 
      - name: local
        hostPath:
          path: /var/nginxserver
  
         
         